### ISSUE TITLE
AVM FritzBox 7490

### ISSUE THREAD

**Issue by alkoforumm** [lede-project/staging#19]
Hey,
I wonder if the Device could be supported ? I know that DECT was never supported and I would not need that if it is the last thing that prevent it.
http://www.wehavemorefun.de/fritzbox/FRITZ!Box_Fon_WLAN_7490

Wireless Chips:
Qualcom / Atheros QCA9880-BR4A
Qualcom / Atheros QCA9558-AT4A

http://www.wehavemorefun.de/fritzbox/FRITZ!Box_Fon_WLAN_7490
https://wiki.openwrt.org/toh/avm/fritzbox.7490 (not quite sure if this is all true)

**Comment by nbd168** [comment]
As far as I know, nobody is planning to work on it at the moment.
