### ISSUE TITLE
WebGUI ?

### ISSUE THREAD

**Issue by ds2k5** [lede-project/staging#5]
Hello,
i build from source the Image: lede-ar71xx-generic-tl-wr941nd-v6-squashfs-factory.bin
and flashed it to my: TP WR941nd.

I tryed to install the WebGUI: luci

root@OpenWrt:~# opkg install luci
Unknown package 'luci'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci.

Is there a WebGUI to install ?

Thanks

**Comment by lynxis** [comment]
Try `opkg update` before try you do `opkg install luci`

**Comment by ds2k5** [comment]
> Try opkg update before

i did this

**Comment by NeoRaider** [comment]
Interesting... while the package luci is found correctly here, it fails for me with the following output:
```
# opkg install luci
Installing luci (git-16.123.28887-219e52e-1) to root...
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/luci/luci_git-16.123.28887-219e52e-1_all.ipk.
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci:
 *      uhttpd *        uhttpd-mod-ubus *       luci-mod-admin-full *   libiwinfo-lua * 
 * opkg_install_cmd: Cannot install package luci.
```

For some reason, the non-target-specific base packages are missing completely, http://downloads.lede-project.org/snapshots/packages/mips_34kc/base/ is empty except for the (empty) package list. I'll see if I can reproduce this locally.

**Comment by jow-** [comment]
The missing base packages should be back with the next build cycle. An nginx misconfiguration on git.lede-project.org broke the ability to do shallow clones which caused builders to be unable to fetch the base feed.

**Comment by ds2k5** [comment]
did a new build, but the same problem:

root@OpenWrt:~# opkg update
Downloading http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/packages/Packages.gz.
Updated list of available packages in /var/opkg-lists/designated_driver_core.
Downloading http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/packages/Packages.sig.
Signature check passed.
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/base/Packages.gz.
Updated list of available packages in /var/opkg-lists/designated_driver_base.
Downloading http://downloads.lede-project.org/snapshots/packages/mips_34kc/base/Packages.sig.
Signature check passed.
root@OpenWrt:~# opkg install luci
Unknown package 'luci'.
Collected errors:
 * opkg_install_cmd: Cannot install package luci.

**Comment by blogic** [comment]
you did not select the luci feed hence luci cannot be found. please edit /etc/opkg/distfeeds.conf and try again
