### ISSUE TITLE
No WLAN Interface on WR941nd Ver. 6.0 - LEDE (r91)

### ISSUE THREAD

**Issue by ds2k5** [lede-project/staging#6]
Hello,
on a TP Link WR941nd Ver. 6.0 i did not had a WLAN Interface.

What i need to enable at build ( make menuconfig )
to get a working WLAN Interface ?

Thanks

**Comment by NeoRaider** [comment]
If you don't have a WLAN interface at all (*/etc/config/wireless* does not exist or is empty), you are missing the ath9k kernel module. This should be selected by default for ar71xx.

**Comment by ds2k5** [comment]
Hi NeoRaider,

>you are missing the ath9k kernel module

the kernel Modules ath9k are loaded.


>This should be selected by default for ar71xx.

i did select this

Is it possible, i know there was a fix
for this Model / version for OpenWRT
it is not a CN Version.

did not find the fix .. sorry

**Comment by NeoRaider** [comment]
I've checked this and I can't reproduce this. The WLAN adapter is found, has an entry in */etc/config/wireless* and can be enabled by removing the *disabled* option from this file on my TL-WR941ND v6. If you still can't find the problem, please try a newer LEDE version (I've tested using r234).

**Comment by ds2k5** [comment]
the file: /etc/config/wireless do not exist

root@OpenWrt:~# lsmod 
ath                    19493  3 ath9k
ath9k                  88774  0 
ath9k_common           19182  1 ath9k
ath9k_hw              336961  2 ath9k
cfg80211              215491  4 ath9k
compat                  3899  4 ath9k

**Comment by ds2k5** [comment]
now i got the new image:



git clone https://github.com/lede-project/staging

cd staging

make menuconfig  (select the target profile: wr941n/nd)

make

scp lede-ar71xx-generic-tl-wr941nd-v6-squashfs-factory.bin root@<ip>:/tmp

sysupgrade -v /tmp/lede-ar71xx-generic-tl-wr941nd-v6-squashfs-factory.bin


but the same, no interface for wlan

root@OpenWrt:~# lsmod | grep ath
ath                    19493  3 ath9k
ath9k                  88774  0 
ath9k_common           19182  1 ath9k
ath9k_hw              336961  2 ath9k
cfg80211              215491  4 ath9k
compat                  3899  4 ath9k
mac80211              392218  1 ath9k

**Comment by NeoRaider** [comment]
Please provide a kernel log (output of `dmesg`) and syslog (output of `logread`).

**Comment by ds2k5** [comment]
hope it helps

[logs.zip](https://github.com/lede-project/staging/files/253843/logs.zip)

thanks for your help!

**Comment by NeoRaider** [comment]
Your log suggests that the ART partition (the last flash partition) has been corrupted.

```
[    9.309710] ath: phy0: eeprom contains invalid mac address: ef:ff:bf:af:5f:7f
[    9.317105] ath: phy0: random mac address will be used: ea:69:25:a3:f8:42
[    9.325707] ath: EEPROM regdomain: 0xefaf
[    9.325716] ath: EEPROM indicates we should expect a country code
[    9.325735] ath: invalid regulatory domain/country code 0xafaf
[    9.325742] ath: Invalid EEPROM contents
```

**Comment by ds2k5** [comment]
thanks, how can i fix this ?

**Comment by AndrewMargarit** [comment]
You can have a look here -https://wiki.openwrt.org/doc/howto/restore_art_partition 
Although if you have not tampered with it, you might have some NOR ( hardware memory ) problem.
